## Bài 6

In [1]:
x = [2.36, 2.37, 2.38, 2.39]
f =  [0.85866, 0.86289, 0.86710, 0.87129]
h = 0.01
fp = (-1.5*f[0] + 2*f[1] - 0.5*f[2]) / h
fpp = (2*f[0] - 5*f[1] + 4*f[2] - f[3])/ h/h

print("f'(2.36) = ",fp)
print("f''(2.36) = ",fpp)


f'(2.36) =  0.42400000000001326
f''(2.36) =  -0.20000000000020002


## Bài 8

In [7]:
x = [0.84, 0.92, 1.00, 1.08, 1.16]
f =  [0.431711, 0.398519, 0.367879, 0.339596, 0.313486]
h = 0.08

fpp = (1*f[2] - 2*f[3] + 1*f[4])/ h/h

print("f''(1) = ",fpp)

f''(1) =  0.33953124999999695


## Bài 9

In [2]:
x = [0, 0.1, 0.2, 0.3, 0.4]
f =  [0, 0.078348, 0.138910, 0.192916, 0.244981 ]
h = 0.1
fp= (-f[2]+f[3])/h
fpp = (1*f[2] - 2*f[3] + 1*f[4])/ h/h

print("O(h)...f''(0.2) = ",fp)

O(h)...f''(0.2) =  0.54006


In [3]:
import scipy
import numpy as np
from scipy.linalg import lu
A = np.array([[1, 2, 3], [2, 7, -4], [9, -4, 15]])
B = np.array([7, 18, 7])
X = np.linalg.inv(A).dot(B)

print(X)

A = np.array([[1, 2, 3], [2, 7, -4], [9, -4, 15]])
B = np.array([7, 18, 7])
P,L, U = scipy.linalg.lu(A)
print("A:")
print(A)

print("P:")
print(P)

print("L:")
print(L)

print("U:")
print(U)
PLU=np.dot(P,np.dot(L, U))
print('PLU:\n',PLU)
Y=np.dot(np.linalg.inv(P),B)
Z=np.dot(np.linalg.inv(L),Y)
X=np.dot(np.linalg.inv(U),Z)
print("X:")
print(X)

[1.3125 2.375  0.3125]
A:
[[ 1  2  3]
 [ 2  7 -4]
 [ 9 -4 15]]
P:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
[[1.         0.         0.        ]
 [0.22222222 1.         0.        ]
 [0.11111111 0.30985915 1.        ]]
U:
[[ 9.         -4.         15.        ]
 [ 0.          7.88888889 -7.33333333]
 [ 0.          0.          3.6056338 ]]
PLU:
 [[ 1.  2.  3.]
 [ 2.  7. -4.]
 [ 9. -4. 15.]]
X:
[1.3125 2.375  0.3125]
